#
# Uses the Scala Steward GitHub Action to upgrade dependencies.
#

name: Scala Steward

on:
  schedule:
    - cron: "0 0 * * SAT"

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    name: Scala Steward
    runs-on: ubuntu-latest
    steps:
      - uses: scala-steward-org/scala-steward-action@v2
